Feat/suggester status
InseeFr/Lunatic pull request #460
Opened 2023-03-01 16:16 UTC by renaud23

Fournir le statut des suggesters à l'utilisateur. 
J'ai réalisé quelques ajustement pour cela :
- j'ai viré suggester des params de useLunatic : ils sont déjà dans source.
- j'ai remplacé la fonction suggesterFetcher qui imposé fetch à l'utilisateur par une fonction au comportement plus générique
- j'ai ajouté useSuggesters dans useLunatic. Il charge les suggester si auto est à true et transmet une fonction qui permet aux composants de suggestion de suivre leur état de chargement, quand on tombe sur eux, au fil du questionnaire.
- un composant SuggesterNotification, customisable, permet de notifier l'utilisateur du cycle de chargement, s'il arrive sur un suggester.
- 5 états sont possibles : 
unuse : quand autoload = false
idle : au dépard, avant le début du chargement
pending : en cour de chargement
success 
error
unknown : référentiel inconnu (un composant suggester mais pas d'entrée correspondante dans la section suggester du source)

Les ajustestements côté queen seront mineures

2023-03-01 23:18 UTC, laurentC35 requested changes
Top dans l'ensemble, on ne casse pas l'interface existant avec les orchestrateur ! 👍 
- Il faudrait adapté le .gitignore, tu as des dossier `dist` et des fichiers dans ces dossiser qui apparaissent dans le commit
- Peut-on ajouter une props pour activer/desactiver le SuggesterNotification (au moins pour l'info)

2023-03-01 23:18 UTC, laurentC35 commented on src/components/suggester/suggester-notification.js
> +function SuggesterNotification({ children, status, storeName }) {
Peut-on ajouter une props (à true par défault) pour activer / désactiver cette notification ou un composant custom qui renvoie juste `children` suffit ?

2023-03-01 23:18 UTC, laurentC35 commented on src/use-lunatic/initial-state.ts
> +	getSuggesterStatus: (name: string) => SuggesterStatus.unused,
Problème de typage visiblement à résoudre (cf CI de test)

2023-03-01 23:18 UTC, laurentC35 commented on src/components/suggester/suggester-status.js
> +		<SuggesterNotification status={status} storeName={storeName}>
Ajouter props pour activer / désactiver notification

2023-03-03 08:12 UTC, renaud23 commented on src/components/suggester/suggester-notification.js
> +function SuggesterNotification({ children, status, storeName }) {
ce qui rend véritablement active les notifications, c'est autoSuggesterLoading à true. C'est déja un peu le cas en fait.

2023-03-03 08:13 UTC, renaud23 commented on src/use-lunatic/initial-state.ts
> +	getSuggesterStatus: (name: string) => SuggesterStatus.unused,
j'ai corrigé. merci.

2023-03-03 08:35 UTC, renaud23 commented on src/components/suggester/suggester-status.js
> +		<SuggesterNotification status={status} storeName={storeName}>
je vais essayé de rendre les choses un peu plus explicite.

2023-03-03 09:15 UTC, renaud23 commented on src/components/suggester/suggester-status.js
> +		<SuggesterNotification status={status} storeName={storeName}>
J'ai ajouté cela dans SuggesterStatus. Les notifications s'affichent pas quand status === unused. C'est useSuggester qui met ce status si auto = false. Avant c'était fait de manière implicite pas SuggNotification (c'était le renvoie par défaut du composant)
`
if (status === SuggesterStatus.unused) {
		return children;
	}
`

2023-03-03 09:22 UTC, closed without merging