une fonction d'ordre supplémentaire, pour ressembler à meloto
InseeFr/Lunatic pull request #486
Opened 2023-03-28 07:14 UTC by renaud23

DRTI me demande d'implémenter une fonction de tri supplémentaire pour le suggester, pour le faire ressembler un peu plus à méloto.
La première fonction de tri compte le nombre tokens de recherche trouvés au sein de l'entité.
La nouvelle calcul un score selon l'index des tokens au sein d'une chaine de de référence (label) pour réordonner les entités de même score (celui obtenu à la première étape)

2023-03-28 09:03 UTC, Grafikart requested changes

2023-03-28 09:04 UTC, Grafikart commented
Aussi peut être ajouté des tests ne serait pas trop mal pour comprendre l'effet de l'organisation et voir des cas d'exemples.

2023-03-28 10:35 UTC, renaud23 commented
oki. je m'y met.

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
From: Jonathan ***@***.***>
Sent: Tuesday, March 28, 2023 11:05:04 AM
To: InseeFr/Lunatic ***@***.***>
Cc: Renaud Genevois ***@***.***>; Author ***@***.***>
Subject: Re: [InseeFr/Lunatic] une fonction d'ordre supplémentaire, pour ressembler à meloto (PR #486)


Aussi peut être ajouté des tests ne serait pas trop mal pour comprendre l'effet de l'organisation et voir des cas d'exemples.

—
Reply to this email directly, view it on GitHub<https://github.com/InseeFr/Lunatic/pull/486#issuecomment-1486484332>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABKTUISI2WEC6OL6HA34KFDW6KSUBANCNFSM6AAAAAAWKENYL4>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-03-28 13:12 UTC, Grafikart commented on src/utils/suggester-workers/searching/meloto-order.js
> +export function value(entity, tokens) {
Si tu exporte cette fonction je veux bien un renommage pour que son utilisation soit plus claire depuis l'extérieur (value est un peu trop générique)

2023-03-28 13:14 UTC, Grafikart requested changes

2023-04-27 13:11 UTC, renaud23 commented on src/utils/suggester-workers/searching/meloto-order.js
> +	}
oui, il faut juste inverser b et a

2023-05-03 13:51 UTC, merged