controls for roundabout
InseeFr/Lunatic pull request #509
Opened 2023-04-21 09:01 UTC by renaud23

Compilation des contrôles dans le contexte particulier du roundabout.
L'expression de contrôle fournit doit être validé pour chaque unité du rond point.
Ajout de 2 paramètres dans le json, pour les contrôles :
- roundabout : le contrôle est pour un rond point
- iterations : vtl pour dénombrer le nombre de membres

Pour le moment ,livré sans test.

2023-04-21 10:03 UTC, Grafikart requested changes

2023-04-21 10:03 UTC, Grafikart commented on src/use-lunatic/reducer/validate-controls/validation-utils.ts
> +	if (roundabout) {
L'extraction dans une variable me semble pas nécessaire.

```js
if (control.roundabout) {
```

Ou si TS râle

```ts
if ('roundabout' in control && control.roundabout)
```

2023-04-21 10:03 UTC, Grafikart commented on src/use-lunatic/reducer/validate-controls/validate-simple.ts
> +export function validateSimple(
Vu que la fonction original s'appelle resolveControl, resolveSimpleControl me semblerait plus adaptée

2023-04-21 10:03 UTC, Grafikart commented on src/use-lunatic/reducer/validate-controls/validate-roundabout.ts
> +export function validateRoundabout(
Vu que la fonction original s'appelle resolveControl, resolveRoundaboutControl me semblerait plus adaptée

2023-04-21 10:03 UTC, Grafikart commented on src/use-lunatic/reducer/validate-controls/validate-roundabout.ts
> + */
Expliquer l'intention derrière la fonction en premier lieu. Car ce n'est pas évident à la lecture là.

2023-04-21 11:36 UTC, renaud23 commented on src/use-lunatic/reducer/validate-controls/validate-roundabout.ts
> +			}, []);
ça me va.
J'ai complétement ignorer le linkIteration. ça aura une incidence ?

2023-04-21 11:39 UTC, renaud23 commented on src/use-lunatic/reducer/validate-controls/validate-simple.ts
> +	const { control: { value = 'true' } = {} } = control;
héritage d'un temps sans ?.

2023-04-21 11:44 UTC, renaud23 commented on src/use-lunatic/reducer/validate-controls/validation-utils.ts
> +	if (roundabout) {
j'ai ajouté roundabout sur le type de control. TS ne devrait rien dire.

2023-04-21 11:46 UTC, renaud23 commented on src/use-lunatic/reducer/validate-controls/validate-roundabout.ts
> +export function validateRoundabout(
il faut renommer fonction et répertoire !

2023-04-21 11:57 UTC, renaud23 commented on src/use-lunatic/reducer/validate-controls/validate-roundabout.ts
> + */
on va s'en passer

2023-04-21 21:50 UTC, Grafikart commented on src/use-lunatic/reducer/validate-controls/validate-roundabout.ts
> +export function validateRoundabout(
Ah oui je n'avais pas lu le nom des fichiers. Du coup cette remarque peut être ignorée.

2023-04-24 12:36 UTC, laurentC35 requested changes

2023-04-24 12:36 UTC, laurentC35 commented on src/use-lunatic/reducer/resolve-component-controls/resolve-simple-control.ts
> +		if (!result) {
Actuellement c'est l'inverse, on déclenche la condition du contrôle est fausse.
c'est un problème bien déjà identifié lors de la génération du questionnaire par Eno, une négation est ajouté à la condition. Du coup on doit prendre la négation (de la négation) pour effectivement lever le contrôle.

Si tu regardes dans le fichier supprimé "validation-utils.ts" c'est bien quand `if (!result)` qu'on déclenche le contrôle

2023-04-27 09:28 UTC, Grafikart approved these changes
Pour la modification sur les sources je me demande plutôt que de mettre un 

```json
"roundabout": true 
```

(Ce qui implique un nouveau booléen pour chaque cas)
Serait-t-il pas mieux d'avoir un enumérable 

```json
"type": "roundabout" 
```

Ce qui permettrait plus tard d'ajouter de nouveau type de control ?

2023-04-27 09:28 UTC, Grafikart commented on src/use-lunatic/reducer/resolve-component-controls/resolve-roundabout-control.ts
> + * @returns
JSDoc à retirer

2023-05-03 14:12 UTC, merged