Feat: A composant "ComponentSet" to create a `<fieldset>` with a `<legend>` and one or more componants
InseeFr/Lunatic pull request #512
Opened 2023-04-24 13:59 UTC by isMattCoding

#510

2023-04-24 14:10 UTC, Grafikart requested changes
Je pense que tu peux regrouper les stories en un seul fichier. Les autres points sont à corriger

2023-04-24 14:10 UTC, Grafikart commented on src/components/component-set/html/component-set-components.jsx
> +	if (Array.isArray(components)) {
Tu peux faire un early return pour éviter l'imbrication

```jsx
if (!Array.isArray(components)) {
  return null;
}
// Le reste du code
```

2023-04-24 14:10 UTC, Grafikart commented on src/components/component-set/html/component-set-components.jsx
> +		return components.map(function (component) {
Tu ne dois pas retourner un tableau dans le cas d'un FunctionComponent. A la place mettre 

```jsx
return  <>{components.map(...)}</>
```

2023-04-24 14:10 UTC, Grafikart commented on src/components/component-set/html/component-set-components.jsx
> +			}
Trop de condition ici, tu peux combiner

```jsx
if (response && response.name in value) {
    componentValue = value[response.name] ?? '';
}
```

2023-04-24 14:29 UTC, MickaelMenet commented on src/components/component-set/html/component-set.jsx
> +		<fieldset className="lunatic-component-set">
Question posé lors de la réunion, vérifié l'utilisation ou non d'un form pour wrapper un fieldset.

2023-04-24 15:14 UTC, isMattCoding commented on src/components/component-set/html/component-set-components.jsx
> +		return components.map(function (component) {
Tu peux élaborer ? 
Pourquoi il faut pas retourner un tableau ? 
Je pensais le transformer en arrow function aussi, qu'en penses-tu ? 
`return <>{components.map((component => { ... }}</>`

2023-04-24 15:24 UTC, isMattCoding commented on src/components/component-set/html/component-set.jsx
> +		<fieldset className="lunatic-component-set">
J'ai créé une story pour explorer le besoin et les implications dans notre board, story id 342

2023-04-26 19:19 UTC, Grafikart commented on src/components/component-set/html/component-set-components.jsx
> +		return components.map(function (component) {
Pour le tableau, en fait ça ne correspond pas à ce qui est acceptable comme élément du coup la fonction ne satisfait plus la condition pour être un FunctionComponent. Je suis étonné que ça marche sans poser de problème, mais lors du passage en TypeScript ça bloquera.

<img width="794" alt="Capture d’écran 2023-04-26 à 21 18 46" src="https://user-images.githubusercontent.com/395137/234680140-48a7eb9e-8097-4aef-a0d3-8c3a54d85dfb.png">

Pour le second point, oui tant que possible utiliser les arrow fonction dans les map / reduce et filter.

2023-04-26 19:27 UTC, Grafikart requested changes
C'est quasi bon. La proposition de changement de nom de fonction peut être ignoré

2023-04-26 19:27 UTC, Grafikart commented on src/use-lunatic/replace-component-sequence.ts
> + * @returns
La JSDoc (@param et @returns) ne sert pas

2023-04-26 19:27 UTC, Grafikart commented on src/use-lunatic/replace-component-sequence.ts
> +export function replaceComponentSequence(
Pas sûr du nom de la fonction, ça reflète pas trop l'objectif j'ai l'impression, propositions : 

- flattenComponents (si on veux utiliser cette fonction pour d'autres choses)
- hoistComponentSetComponents (pour indiquer qu'on remonte les composants des fieldset)

2023-04-26 19:27 UTC, Grafikart commented on src/use-lunatic/replace-component-sequence.ts
> +			return [...acc, ...components];
peut être réduit en 

```jsx
return [...acc, ...component.components]
```

La destructuration ne me semble pas apporter plus de contexte

2023-04-26 19:27 UTC, Grafikart commented on src/use-lunatic/reducer/reduce-on-init.ts
> -		withOverview,
Sûr de cette suppression ? Car elle ne me semble pas être en rapport avec le sujet de cette PR.

2023-04-27 13:50 UTC, renaud23 commented on src/use-lunatic/reducer/reduce-on-init.ts
> -		withOverview,
pas utilisé dans le fichier ?

2023-04-27 13:57 UTC, renaud23 commented on src/use-lunatic/reducer/reduce-on-init.ts
> -		withOverview,
je confirme, utilisé nul part

2023-05-03 13:57 UTC, Grafikart approved these changes

2023-05-03 14:20 UTC, merged