Feat/alt declarations
InseeFr/Lunatic pull request #517
Opened 2023-04-28 06:35 UTC by renaud23

Proposer de nouveaux composants pour porter du texte autour et dans les composants, de manière plus aisée que les déclarations. Ces dernières ne bouge plus.
La position et le rendu des  nouveaux éléments sont imposés par le designer et non un choix libre de placement, comme pour les déclarations.

2023-05-17 10:56 UTC, isMattCoding requested changes

2023-05-17 10:56 UTC, isMattCoding commented on src/components/commons/components/lunatic-component-without-label.tsx
>  	children: ReactElement;
Est-ce que c'est utile / possible d'utiliser `PropsWithChildren` ?  : 
```
PropsWithChildren<{
   other props
}> & Pick<...> 
```

2023-05-17 10:56 UTC, isMattCoding commented on src/components/questions/question-context .tsx
> +		return <div className="lunatic-call-out">{text}</div>;
`return <div className="lunatic-question-context">{text}</div>;`

2023-05-17 10:56 UTC, isMattCoding commented on src/components/questions/question-information.tsx
> +		return <div className="lunatic-alert-information">{text}</div>;
`return <div className="lunatic-question-information">{text}</div>;`

2023-05-22 14:50 UTC, MickaelMenet approved these changes

2023-05-22 14:50 UTC, MickaelMenet commented on src/components/sequence/sequence.spec.tsx
> +		// expect(sequenceLabel?.nextSibling?.nextSibling?.childNodes[0]).toBe(
remove comment

2023-05-22 14:52 UTC, isMattCoding approved these changes

2023-05-22 14:53 UTC, merged