Fix/workers path
InseeFr/Lunatic pull request #528
Opened 2023-05-03 12:59 UTC by renaud23

reccupération du chemin des workers depuis une fonction plutôt que d'une variable à la racine du script.

2023-05-03 13:56 UTC, Grafikart requested changes

2023-05-03 13:56 UTC, Grafikart commented on .github/workflows/ci-develop.yml
> +  publish_beta_on_npm:
Le formattage de la tâche ne correspond pas au reste, ça devrait être du kebab case : `publish-beta-npm`

2023-05-10 09:40 UTC, ddecrulle commented
Hi process.env are not supported with vite project and are build time environement variable. Could you consider to this issue #518 which deals with the same code part ?

2023-05-10 09:49 UTC, Grafikart approved these changes

2023-05-30 08:39 UTC, closed without merging