Feat: Suggester, dynamic table & dynamicUnit (EAP story)
InseeFr/Lunatic pull request #553
Opened 2023-06-02 14:27 UTC by laurentC35

2023-07-19 14:05 UTC, Grafikart commented on src/components/suggester/lunatic-suggester.tsx
> +				// @ts-ignore
A retirer

2023-07-19 14:05 UTC, Grafikart commented on src/components/type.ts
> +	};
Vestige du rebase je pense, à retirer

2023-07-19 14:05 UTC, Grafikart commented on src/components/type.ts
> +		};
Vestige du rebase je pense, à retirer

2023-07-19 14:05 UTC, Grafikart commented on src/components/type.ts
> +		};
Vestige du rebase je pense, à retirer

2023-07-19 14:05 UTC, Grafikart commented on src/components/type.ts
> +		onSelect?: any;
type any interdit ^^

2023-07-19 14:05 UTC, Grafikart commented on src/use-lunatic/commons/fill-components/fill-component-expressions.ts
> +	'dynamicUnit',
Vestige du rebase je pense, à retirer

2023-07-19 14:05 UTC, Grafikart commented on src/use-lunatic/initial-state.ts
> +	// @ts-ignore
A retirer

2023-07-19 14:05 UTC, Grafikart commented on src/use-lunatic/reducer/reducer.ts
> +			// @ts-ignore
A retirer

2023-07-19 14:06 UTC, Grafikart requested changes
Il reste des vestige des rebases et des commentaires à supprimer

2023-07-20 13:38 UTC, AgatheLM commented on src/components/commons/create-row-orchestrator.tsx
> +	getSuggesterStatus?: LunaticState['getSuggesterStatus'];
J'ai l'impression que la fonction getSuggesterStatus est utile car transmise au composant <Row/> ensuite

2023-07-28 07:15 UTC, AgatheLM commented on src/components/dropdown/lunatic-dropdown.tsx
> +	const onChange: any = useOnHandleChange({ handleChange, response, value });
Je n'arrive pas a résoudre l'erreur typescript

2023-07-28 07:17 UTC, AgatheLM commented on src/components/loop/loop.tsx
> +		getSuggesterStatus,
ok

2023-07-28 07:18 UTC, AgatheLM commented on src/components/loop/roster-for-loop/roster-for-loop-orchestrator.ts
> +// @ts-ignore
Je n'arrive pas à corriger l'erreur typescript, désolé

2023-07-28 07:20 UTC, AgatheLM commented on src/components/loop/roster-for-loop/roster-for-loop.tsx
> +			handleChange(response, v, { loop: true, length: nbRowsRef.current }); // TODO: a retaper pour déplacer cette compléxité
Je veux bien, je n'avais pas bossé sur la partie perf. L'idée pour le tableau dynamique est de faire un re-render uniquement pour la ligne concernée lorsqu'une cellule est modifiée. On a besoin du scope de la ligne pour le rafraichissement de l'unité dyamique

2023-07-28 07:21 UTC, AgatheLM commented on src/components/loop/roster-for-loop/roster-table.tsx
> +	getSuggesterStatus,
ok

2023-07-28 07:37 UTC, AgatheLM commented on src/components/loop/roster-for-loop/row.tsx
> +							}
encore des problèmes typescript, désolé

2023-07-28 07:55 UTC, AgatheLM commented on src/components/suggester/lunatic-suggester.tsx
> +	// @ts-ignore
Je crois que le todo n'était plus utile, je supprime

2023-07-28 09:37 UTC, AgatheLM commented
# Objectifs :


## Input number
- Variabiliser l'untité en fonction d'une formule VTL

## Suggester 
- Enrichir les objets de la nomenclatures avec des clés supplémentaires qui peuvent être utilisées dans des formules VTL 
Par exemple :
```	
{
  "id": "11",
  "label": "Beton",
  "unit": "tonnes"
},
```

## Tableaux dynamiques (rooster-for-loop)

- Améliorer les performances
- Permettre d'utiliser un suggester en component dans une colonne
- Permettre de viabiliser le rendu d'une ligne en fonction d'une formule VTL

2024-05-03 06:20 UTC, ddecrulle commented
Can we close the PR ? All things are completed in 3.0 branch ?

2024-05-11 13:46 UTC, closed without merging

2024-05-19 15:28 UTC, AgatheLM commented
Envoyé depuis mon appareil Galaxy


-------- Message d'origine --------
De : Dylan Decrulle ***@***.***>
Date : 11/05/2024 15:47 (GMT+01:00)
À : InseeFr/Lunatic ***@***.***>
Cc : Agathe Le Meur ***@***.***>, Comment ***@***.***>
Objet : Re: [InseeFr/Lunatic] Feat: Suggester, dynamic table & dynamicUnit (EAP story) (PR #553)

-------- Message d'origine --------
De : Dylan Decrulle ***@***.***>
Date : 11/05/2024 15:47 (GMT+01:00)
À : InseeFr/Lunatic ***@***.***>
Cc : Agathe Le Meur ***@***.***>, Comment ***@***.***>
Objet : Re: [InseeFr/Lunatic] Feat: Suggester, dynamic table & dynamicUnit (EAP story) (PR #553)


Closed #553<https://github.com/InseeFr/Lunatic/pull/553>.

—
Reply to this email directly, view it on GitHub<https://github.com/InseeFr/Lunatic/pull/553#event-12776515957>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIOOWTHYR2IUZJBOJLFC57TZBYONHAVCNFSM6AAAAAAYYMT4H6VHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJSG43TMNJRGU4TKNY>.
You are receiving this because you commented.Message ID: ***@***.***>