suggester work in a component set
InseeFr/Lunatic pull request #582
Opened 2023-06-27 07:24 UTC by renaud23

Le Suggester ne marche pas correctement dans un componentSet. La fonction getsSuggesterStatut n'est pas propagé dans les sous composants.

@Grafikart le typage de la fonction pour étendre les types props des composant est certainement discutable. Je te laisse seul juge.

2023-06-27 09:07 UTC, isMattCoding approved these changes
LGTM, interested to see what @Grafikart thinks of this solution to pass the getSuggesterStatus type to LunaticComponentSet

2023-07-06 11:03 UTC, isMattCoding commented
@renaud23 Je pense qu'on peut passer en Ready for review, tu confirmes ?

2023-07-06 11:23 UTC, Grafikart requested changes

2023-07-06 11:23 UTC, Grafikart commented on src/components/commons/components/orchestrated-component.tsx
> +				getSuggesterStatus={getSuggesterStatus}
Est-ce qu'il ne serais pas judicieux alors de passer toutes les props au composant. Plutôt que spécificier à chaque fois.

```ts

function OrchestratedComponent({
	component,
	 ...props
}: Props) {
	const { componentType } = component;

	const componentFilled = fillComponentExpressions(component, {
		props.executeExpression,
		pager: { iteration: props.iteration, linksIterations: props.linksIterations },
	});

	const hasToBeDisplay = componentFilled.conditionFilter ?? true;

	if (componentType in lunatic && hasToBeDisplay) {
		const Component = (lunatic as any)[componentType]; // This is too dynamic, orchestration has no way to check props
		return (
			<Component
				{...componentFilled}
				executeExpression={executeExpression}
                {...props}
			/>
		);
	}
	return null;
}
```

2023-07-12 15:22 UTC, isMattCoding commented
OK in Lunatic-DSFR
@Grafikart Je te laisse resoudre les conflicts, puis c'est pret à merger

2023-07-17 15:28 UTC, merged