Feat 389/accordion component
InseeFr/Lunatic pull request #587
Opened 2023-07-05 12:40 UTC by aymendebbabi1989

2023-07-06 09:34 UTC, Grafikart requested changes

2023-07-06 09:34 UTC, Grafikart commented on src/components/accordion/html/accordion.tsx
> +            <div className="accordion-title" onClick={() => setIsActive(!isActive)}>
D'un point de vu sémantique cet élément devrait être un <button> , des attributs peuvent aussi être ajouter pour l'accéssibilité (à voir si ça fait partit du cadre de la mission) https://www.w3.org/WAI/ARIA/apg/patterns/accordion/examples/accordion/

2023-07-06 09:34 UTC, Grafikart commented on src/components/accordion/html/accordion.tsx
> +        <div className="accordion-item" style={{ backgroundColor: bgColor ? bgColor : defaultBgcolor }}>
Peut être laisser le CSS gérer la couleur en l'absance de bgColor

2023-07-11 09:59 UTC, Grafikart commented
## Pourquoi ce composant ?

Ce composant a pour but de permettre d'ajouter des information en pied de page (dans le cas du DSFR pour le moment mais d'autres plus tard). Un titre doit être clicable et permettre de révéler du contenu en dessous.

## A faire

- [ ] Trouver un meilleur nommage car le composant n'est pas un accordeon (un seul élément)
- [ ] Réfléchir à l'approche, est ce logique de créer un nouveau composant dans le cadre de la présentation. Car tous les orchestrateurs vont devoir implémenter la logique pour placer ce composant en bas de page.

2023-07-13 08:53 UTC, isMattCoding commented
> * [ ]  Trouver un meilleur nommage car le composant n'est pas un accordeon (un seul élément)

Je suis d'accord, je propose de suivre le nommage d'autres composants ajoutés auparavant (QuestionContext et QuestionInformation) : QuestionExplication.

> * [ ]  Réfléchir à l'approche, est ce logique de créer un nouveau composant dans le cadre de la présentation. Car tous les orchestrateurs vont devoir implémenter la logique pour placer ce composant en bas de page.

En soit, c'est une question UI, dans Stromae on a décidé de placer ce composant d'une certaine mannière, mais rien n'empeche que ça soit affiché autrement dans d'autres orchestrateurs.

2023-07-13 12:24 UTC, Grafikart commented
@isMattCoding @aymendebbabi1989  Est ce que le nommage est en anglais en général ? Si oui, "QuestionDetail" semble  plus adapté (car Explication c'est français).

Aussi, vu que c'est un nouveau composant il faudrait ajouter les types dans les sources que peut recevoir lunatic `type-source.ts`

2023-07-17 15:29 UTC, Grafikart commented
Un petit rebase est nécessaire sur cette branche

2023-07-31 14:13 UTC, merged