customizableField instead of components in props for Combobox
InseeFr/Lunatic pull request #618
Opened 2023-07-31 07:28 UTC by renaud23

La customisation du suggester et du dropdown passe dorénavant par createCustomizableField avec les nom ComboboxDisplayLabel, ComboboxInput, ComboboxOption et ComboboxDelete.
Les props optionRenderer et labelRenderer sont marquées deprecated.
J'ai aussi supprimé le hoc displayLabelOrInput pour le remplacer par un simple composant, en espérant ne pas introduire de régression.

2023-07-31 13:58 UTC, Grafikart requested changes
Juste des remarques au niveau du nommage et ça sera bon pour moi

2023-07-31 13:58 UTC, Grafikart commented on src/components/commons/components/combo-box/selection/delete.tsx
> +function DeleteCmp({ className, search, onClick, editable }: Props) {
En profiter pour renommer ce composant pour un nom plus clair, `clearButton` par exemple

2023-07-31 13:58 UTC, Grafikart commented on src/components/commons/components/combo-box/selection/delete.tsx
> +	'ComboboxDelete'
ComboboxClearButton du coup

2023-07-31 13:58 UTC, Grafikart commented on src/components/commons/components/option-renderer.tsx
> +	'ComboboxOptionRenderer'
ComboboxOption me semble plus simple

2023-08-07 12:57 UTC, renaud23 commented
J'ai revu au final ce que j'avais fais pour dissocier clairement la pratique deprecated et la nouvelle manière de faire.

2023-08-08 05:36 UTC, Grafikart requested changes
Pas de problèmes sur la logique, 2 nommages à changer

2023-08-08 05:36 UTC, Grafikart commented on src/components/commons/components/combo-box/panel/panel.tsx
> +	const EffectifRenderer = OptionRenderCustom ?? ComboBoxOption;
Tu peux mettre ça dans les paramètres de la fonction ? 

```js
export function Panel({
	optionRenderer: OptionRender = ComboBoxOption,
	optionRenderer: OptionRenderCustom,
    // ...
```

2023-08-08 05:36 UTC, Grafikart commented on src/components/commons/components/combo-box/selection/LabelOrInput.tsx
> +export function LabelOrInput(props: LabelOrInputType) {
Si tu peux juste rajouter un commentaire pour expliquer le rôle de ce composant

2023-08-08 05:36 UTC, Grafikart commented on src/components/commons/components/combo-box/selection/LabelOrInput.tsx
> +type LabelOrInputType = LabelSelectionProps &
Par convention tu peux nommer le type "Props"

2023-08-08 05:36 UTC, Grafikart commented on src/components/commons/components/combo-box/selection/label-selection.tsx
> +	const EffectifRenderer = Renderer ?? ComboBoxLabelSelection;
Quand on parle de composant mieux vaut nommer Component.  Renderer fait plutôt penser à une fonction.

```js
const LabelComponent = Renderer ?? ComboBoxLabelSelection
```

2023-08-08 14:42 UTC, laurentC35 approved these changes

2023-08-09 08:35 UTC, Grafikart approved these changes

2023-08-09 08:50 UTC, merged