add disabled attribute in lunatic to disabled a single component from…
InseeFr/Lunatic pull request #628
Opened 2023-08-02 14:01 UTC by renaud23

… a VTL expression

2023-08-03 08:06 UTC, Grafikart requested changes
Il faut modifier le type dans les sources et aussi le model lunatic pour indiquer ce qui est attendu dans disabled (en plus ce n'est pas forcément présent pour tous les composants j'imagine).

Aussi, petit réflexion entre "disabled" et "readonly" car ça n'a pas la même signification niveau HTML. un champs readonly peut être focus là ou un champs disabled ne peut pas l'être. Donc à voir si le nom de la propriété correspond bien à ce que l'on veut ou si cela doit être renommé "readonly".

2023-08-30 12:19 UTC, isMattCoding commented
> Il faut modifier le type dans les sources et aussi le model lunatic pour indiquer ce qui est attendu dans disabled (en plus ce n'est pas forcément présent pour tous les composants j'imagine).

J'ai du mal a comprendre, je vois dans LunaticBaseProps on a déjà typé `disabled` et `readOnly`. Comment faudrait-il le modifier ? 

> Aussi, petit réflexion entre "disabled" et "readonly" car ça n'a pas la même signification niveau HTML. un champs readonly peut être focus là ou un champs disabled ne peut pas l'être. Donc à voir si le nom de la propriété correspond bien à ce que l'on veut ou si cela doit être renommé "readonly".

Pour notre besoin, il s'agit bien d'un readOnly qu'on veut, une variable pre-rempli que l'on peut voir mais ne peut pas modifier.

2023-09-18 11:44 UTC, laurentC35 commented
ToDo

- [ ] Input
- [ ] InputNumber
- [ ] Radio
- [ ] CheckBox
- [ ] Textarea
- [ ] Dropdown
- [ ] Datepicker
- [ ] Suggester
- [ ] Switch

2023-09-18 12:34 UTC, isMattCoding commented
I reverted the changes affecting the combobox as #683 is in progress. 
I pushed a [branch ](https://github.com/InseeFr/Lunatic/tree/feat/disabled-combobox) which includes the changes for dropdown/suggester, which we likely won't use because of conflicts with #683, but it gives an idea of what's required

2023-09-18 12:35 UTC, isMattCoding commented
> Verify :
>     * ComponentSet
>     * Table
>     * PairwiseLink

I checked these components, and the feature seems to work correctly.

2023-09-19 07:26 UTC, ddecrulle commented
Take care you have accidentally imported read from the fs package

2023-09-19 07:27 UTC, ddecrulle requested changes

2023-09-19 07:27 UTC, ddecrulle commented on src/components/commons/components/combo-box/combo-box.tsx
> +import { read } from 'fs';
Take care you have accidentally imported `read` from the `fs` package

2023-09-19 11:46 UTC, laurentC35 commented
Fix : https://github.com/InseeFr/Lunatic/issues/692 ?

2023-09-20 08:03 UTC, Grafikart approved these changes

2023-09-20 08:03 UTC, merged