Feat/modal component
InseeFr/Lunatic pull request #631
Opened 2023-08-08 15:23 UTC by isMattCoding

**Figma Mockup** 
![image](https://github.com/InseeFr/Lunatic/assets/87824367/dcf47f20-2712-4df4-ac91-590c18308fd9)

**Specs** 
The Modal component can be added at any point during a questionnaire, at the wishes of the creater of the questionnaire. 
It is intended to be used at the end of a section of a questionnaire to incite a user to confirm their previous responses before continuing/finishing. 
A user can cancel or close the modal, these actions should mimic the `Precedent` button. 
A user can confirm their responses, this action should mimic the `Continuer` button. 

**Constraints**
In a regular Lunatic component, we cannot access `goNextPage` or `goPreviousPage`.  We can only access `goToPage(n)`. 
If the modal is on page `x` and there is a condition filter on all of the components on page `x + 1`, then `goToPage(x + 1)` is not satisfactory, as it will navigate to a page that is empty. 
This can be fixed either by ensuring that the pages `x + 1` and `x - 1` display something regardless of any condition filters. 
Alternatively (as will be the case for Stromae-v3) the functions `goNextPage` and `goPreviousPage` can be passed down to this component, and if they are present, these functions are used instead of `goToPage(x +/- 1)`.

2023-08-09 06:33 UTC, laurentC35 commented
Bonjour,
Il y a une archive au format .tgz dans les fichiers que tu as push.

2023-08-09 08:48 UTC, Grafikart requested changes
Peut être injecter goNextPage / goPreviousPage dans les composants directement (getComponents() de useLunatic) pour que les orchestrateurs n'ai rien à faire.

2023-08-09 08:48 UTC, Grafikart commented on src/components/modal/html/modal.tsx
> +						<a onClick={handlePreviousClick}>fermer x</a>
Cela devrait être un bouton

2023-08-09 08:48 UTC, Grafikart commented on src/components/modal/html/modal.tsx
> +					</div>
Ajouter un markup plus sémantique h2 / p ?

2023-08-09 08:55 UTC, laurentC35 commented on src/components/modal/html/modal.tsx
> +	);
Je suis d'accord avec ça

2023-08-09 11:21 UTC, isMattCoding commented on src/components/modal/html/modal.tsx
> +	);
J'ai injecté ces fonctions dans ma [dernière commit](https://github.com/InseeFr/Lunatic/pull/631/commits/014d7bfc4d63fb3f4b7138cbcc8befef754c3f29), mais j'aimerai bien que quelqu'un regarde pour voir si j'ai bien fait 😅

2023-08-11 13:43 UTC, isMattCoding commented on src/components/modal/html/modal.tsx
> +					</div>
Je voulais éviter cela parce que j'envisage que les concepteurs vont vouloir ajouter du MD.  J'envisage qu'on va vouloir ajouter des <ul> dans la partie description, par exemple.

2023-08-21 13:06 UTC, Grafikart approved these changes

2023-08-21 15:50 UTC, merged