New "LunaticComponents" for orchestrator
InseeFr/Lunatic pull request #664
Opened 2023-09-12 11:12 UTC by Grafikart

## Problem

We want lunatic to autofocus the first field, it's a behaviour common on multiple orchestrators. 

- Orchestrators uses an array of components to  mount lunatic and there is no common wrapper around field
- Code within orchestrator (the `components.map()` is a bit to complicated in my taste and duplicated between orchestrators

## Solution

Create a new components that is responsible to display all the fields, while retaining the level of customization required for orchestrator.

```

```

2023-09-12 11:36 UTC, ddecrulle requested changes

2023-09-12 11:36 UTC, ddecrulle commented on src/components/lunatic-components.tsx
> +	ReactNode,
it's type and should be imported as it

2023-09-12 11:36 UTC, ddecrulle commented on src/components/lunatic-components.tsx
> +import { ItemOf } from '../type.utils';
type again

2023-09-12 11:36 UTC, ddecrulle commented on src/components/lunatic-components.tsx
> +		</div>
This is perhaps redundant with the possibility of having a wrapper. I think it's more intuitive to render the component directly, except to add this div by default in the wrapper function.

2023-09-12 12:27 UTC, ddecrulle approved these changes
Good ! Take care this is major change, even if orchestrators can still work with the "old way" of orchestration, it's important to support the change by documenting the README

2023-09-14 09:41 UTC, laurentC35 approved these changes
Nice !
It fix also :
- https://github.com/InseeFr/Lunatic/issues/396

2023-09-18 08:11 UTC, laurentC35 commented
Can you add a minimal doc on README.md about the new feature : `autoFocusKey` ?
Thanks

2023-09-18 08:12 UTC, laurentC35 requested changes
Can you add a minimal doc on README.md about the new feature : `autoFocusKey` (like description of your PR)
Thanks

2023-09-18 14:51 UTC, merged