Spec : New component : "Autres préciser" / "Other" (Checkbox, checkBoxOne)
InseeFr/Lunatic pull request #750
Opened 2023-11-02 12:01 UTC by Grafikart

## Problem

On some form we want to add an option to allow an additional answer for specific field

## Solution

There is not lunatic modelisation for this feature so this PR is a proof of concept and spec. The field is triggered adding extra properties on the "responses" field : 

```diff
{
	"id": "kmort6x9-QOP-kmorue9d",
	"label": {
		"value": "\"Autre\"",
		"type": "VTL"
	},
	"response": { "name": "NATIO1N5" },
+	"detail": {
+		"label": {
+			"value": "\"Préciser : \"",
+			"type": "VTL"
+		},
+		"response": {
+			"name": "NATIO1N5DETAIL"
+		}
+	}
}
```

## Render 

![image](https://github.com/InseeFr/Lunatic/assets/395137/c6ec7f43-ebc7-4626-9485-f569c8747e83)

## Extra

While working on this feature I refactored the CheckboxGroup component to use a native checkbox input as a base.

Fix #204

2023-11-02 13:08 UTC, laurentC35 requested changes
Dans la story sur le autre précisez, il manque la variable `NATIO1N5DETAIL` dans le tableau des variables COLLECTED.

Some unit test, don't succeed

2023-11-02 13:08 UTC, laurentC35 commented on src/components/checkbox/commons/checkbox-option.tsx
> +					onChange={(e) => handleChange(e.target.checked)}
La fonction est définie ici, un re-rendu inutile peut-être ?

2024-03-20 09:40 UTC, nsenave commented
I'm ok with this modelling, I would just need to know the comprehensive list of components that can have this `"detail"` property. 

Is this only for `CheckboxGroup`? or also for `CheckboxBoolean` and `Radio`. And if so:

- what about `Dropdown`?
- what about the case when these components would be in a `Table` (would it be forbidden, or...?)

PS: on the naming, the idea of `"otherPleaseSpecify"` came to my mind (longer, a bit weird, but a bit clearer imo, just an idea though)

2024-03-20 09:55 UTC, nsenave commented
Discussed with @AnneHuSKa : the "detail" is not expected to work if the component is within a table.

2024-04-24 07:41 UTC, laurentC35 commented on src/utils/event.ts
> +		console.log(e.key);
You should remove console.log ?

2024-05-03 06:20 UTC, closed without merging

2024-05-03 06:22 UTC, ddecrulle commented
Completed in another PR