feat: internal link
InseeFr/Lunatic pull request #791
Opened 2023-11-20 14:56 UTC by ddecrulle

2023-11-21 15:39 UTC, Grafikart requested changes

2023-11-21 15:39 UTC, Grafikart commented on src/components/commons/components/md-label/router-link.tsx
> +		<a href={to} onClick={onClick} ref={ref} {...rest}>
La destructuration ne sert à rien pour onClick ref et children

2023-11-21 15:39 UTC, Grafikart commented on tests/setup.ts
> +global.ResizeObserver = vi.fn().mockImplementation(() => ({
Ajouter un commentaire pour expliquer ce code.

2023-11-21 15:39 UTC, Grafikart commented on src/components/commons/components/md-label/link.tsx
> +		if (href.trim().startsWith('/')) {
On ne pourrait pas avoir des liens relatif aussi genre "./blog"

2023-11-21 15:39 UTC, Grafikart commented on src/components/commons/components/md-label/link.tsx
>  			>
autant calculé toutes les props en amont car niveau lisibilité c'est pas top là :(

2023-11-21 18:04 UTC, ddecrulle commented on src/components/commons/components/md-label/link.tsx
> +		if (href.trim().startsWith('/')) {
Je vois pas trop de cas d’usage pour ça t’en as en tête ?

2023-11-22 07:27 UTC, ddecrulle commented on src/components/commons/components/md-label/router-link.tsx
> +		<a href={to} onClick={onClick} ref={ref} {...rest}>
Pour children je pense que c'est bien de le laisser.

2023-11-22 15:03 UTC, laurentC35 approved these changes

2023-11-22 15:04 UTC, merged